# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/h6lp',
                'doc_host': 'https://klmrgrss.github.io',
                'git_url': 'https://github.com/klmrgrss/h6lp',
                'lib_path': 'h6lp'},
  'syms': {'h6lp.core': {'h6lp.core.foo': ('core.html#foo', 'h6lp/core.py')}}}
